package borys.parser;

public interface ConstantStringValues {
	String SCRIPT_DELETION_INPUT = "<head>\r\n" + "<meta charset=\"UTF-8\"/>\r\n"
			+ "<title>Aerospace - Wikipedia</title>\r\n"
			+ "<script>document.documentElement.className=\"client-js\";RLCONF={\"wgBreakFrames\":!1,\"wgSeparatorTransformTable\":[\"\",\"\"],\"wgDigitTransformTable\":[\"\",\"\"],\"wgDefaultDateFormat\":\"dmy\",\"wgMonthNames\":[\"\",\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"],\"wgRequestId\":\"X-svqApAICAAAGjw1HkAAAAP\",\"wgCSPNonce\":!1,\"wgCanonicalNamespace\":\"\",\"wgCanonicalSpecialPageName\":!1,\"wgNamespaceNumber\":0,\"wgPageName\":\"Aerospace\",\"wgTitle\":\"Aerospace\",\"wgCurRevisionId\":996914299,\"wgRevisionId\":996914299,\"wgArticleId\":154711,\"wgIsArticle\":!0,\"wgIsRedirect\":!1,\"wgAction\":\"view\",\"wgUserName\":null,\"wgUserGroups\":[\"*\"],\"wgCategories\":[\"Webarchive template wayback links\",\"CS1 maint: archived copy as title\",\"Aerospace\"],\"wgPageContentLanguage\":\"en\",\"wgPageContentModel\":\"wikitext\",\"wgRelevantPageName\":\"Aerospace\",\"wgRelevantArticleId\":154711,\"wgIsProbablyEditable\":!0,\"wgRelevantPageIsProbablyEditable\":!0,\"wgRestrictionEdit\":[],\"wgRestrictionMove\":[\r\n"
			+ "],\"wgMediaViewerOnClick\":!0,\"wgMediaViewerEnabledByDefault\":!0,\"wgPopupsReferencePreviews\":!1,\"wgPopupsConflictsWithNavPopupGadget\":!1,\"wgPopupsConflictsWithRefTooltipsGadget\":!0,\"wgVisualEditor\":{\"pageLanguageCode\":\"en\",\"pageLanguageDir\":\"ltr\",\"pageVariantFallbacks\":\"en\"},\"wgMFDisplayWikibaseDescriptions\":{\"search\":!0,\"nearby\":!0,\"watchlist\":!0,\"tagline\":!1},\"wgWMESchemaEditAttemptStepOversample\":!1,\"wgULSCurrentAutonym\":\"English\",\"wgNoticeProject\":\"wikipedia\",\"wgCentralAuthMobileDomain\":!1,\"wgEditSubmitButtonLabelPublish\":!0,\"wgULSPosition\":\"interlanguage\",\"wgWikibaseItemId\":\"Q2876213\"};RLSTATE={\"ext.globalCssJs.user.styles\":\"ready\",\"site.styles\":\"ready\",\"noscript\":\"ready\",\"user.styles\":\"ready\",\"ext.globalCssJs.user\":\"ready\",\"user\":\"ready\",\"user.options\":\"loading\",\"ext.cite.styles\":\"ready\",\"skins.vector.styles.legacy\":\"ready\",\"ext.visualEditor.desktopArticleTarget.noscript\":\"ready\",\"ext.uls.interlanguage\":\"ready\",\"ext.wikimediaBadges\":\"ready\",\r\n"
			+ "\"wikibase.client.init\":\"ready\"};RLPAGEMODULES=[\"ext.cite.ux-enhancements\",\"site\",\"mediawiki.page.ready\",\"mediawiki.toc\",\"skins.vector.legacy.js\",\"ext.gadget.ReferenceTooltips\",\"ext.gadget.charinsert\",\"ext.gadget.extra-toolbar-buttons\",\"ext.gadget.refToolbar\",\"ext.gadget.switcher\",\"ext.centralauth.centralautologin\",\"mmv.head\",\"mmv.bootstrap.autostart\",\"ext.popups\",\"ext.visualEditor.desktopArticleTarget.init\",\"ext.visualEditor.targetLoader\",\"ext.eventLogging\",\"ext.wikimediaEvents\",\"ext.navigationTiming\",\"ext.uls.compactlinks\",\"ext.uls.interface\",\"ext.cx.eventlogging.campaigns\",\"ext.centralNotice.geoIP\",\"ext.centralNotice.startUp\"];</script>\r\n"
			+ "<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.implement(\"user.options@1hzgi\",function($,jQuery,require,module){/*@nomin*/mw.user.tokens.set({\"patrolToken\":\"+\\\\\",\"watchToken\":\"+\\\\\",\"csrfToken\":\"+\\\\\"});\r\n"
			+ "});});</script>\r\n"
			+ "<link rel=\"stylesheet\" href=\"/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cskins.vector.styles.legacy%7Cwikibase.client.init&amp;only=styles&amp;skin=vector\"/>\r\n"
			+ "<script async=\"\" src=\"/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector\"></script>\r\n"
			+ "<meta name=\"ResourceLoaderDynamicStyles\" content=\"\"/>\r\n"
			+ "<link rel=\"stylesheet\" href=\"/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector\"/>\r\n"
			+ "<meta name=\"generator\" content=\"MediaWiki 1.36.0-wmf.25\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin-when-crossorigin\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin-when-cross-origin\"/>\r\n"
			+ "<meta property=\"og:image\" content=\"https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Top_of_Atmosphere.jpg/1200px-Top_of_Atmosphere.jpg\"/>\r\n"
			+ "<link rel=\"preconnect\" href=\"//upload.wikimedia.org\"/>\r\n"
			+ "<link rel=\"alternate\" media=\"only screen and (max-width: 720px)\" href=\"//en.m.wikipedia.org/wiki/Aerospace\"/>\r\n"
			+ "<link rel=\"alternate\" type=\"application/x-wiki\" title=\"Edit this page\" href=\"/w/index.php?title=Aerospace&amp;action=edit\"/>\r\n"
			+ "<link rel=\"edit\" title=\"Edit this page\" href=\"/w/index.php?title=Aerospace&amp;action=edit\"/>\r\n"
			+ "<link rel=\"apple-touch-icon\" href=\"/static/apple-touch/wikipedia.png\"/>\r\n"
			+ "<link rel=\"shortcut icon\" href=\"/static/favicon/wikipedia.ico\"/>\r\n"
			+ "<link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/w/opensearch_desc.php\" title=\"Wikipedia (en)\"/>\r\n"
			+ "<link rel=\"EditURI\" type=\"application/rsd+xml\" href=\"//en.wikipedia.org/w/api.php?action=rsd\"/>\r\n"
			+ "<link rel=\"license\" href=\"//creativecommons.org/licenses/by-sa/3.0/\"/>\r\n"
			+ "<link rel=\"canonical\" href=\"https://en.wikipedia.org/wiki/Aerospace\"/>\r\n"
			+ "<link rel=\"dns-prefetch\" href=\"//login.wikimedia.org\"/>\r\n"
			+ "<link rel=\"dns-prefetch\" href=\"//meta.wikimedia.org\" />\r\n" + "</head>";
	String SCRIPT_DELETION_EXPECTATION = "<head>\r\n" + "<meta charset=\"UTF-8\"/>\r\n"
			+ "<title>Aerospace - Wikipedia</title>\r\n" + "\r\n" + "\r\n"
			+ "<link rel=\"stylesheet\" href=\"/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediaBadges%7Cskins.vector.styles.legacy%7Cwikibase.client.init&amp;only=styles&amp;skin=vector\"/>\r\n"
			+ "\r\n" + "<meta name=\"ResourceLoaderDynamicStyles\" content=\"\"/>\r\n"
			+ "<link rel=\"stylesheet\" href=\"/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector\"/>\r\n"
			+ "<meta name=\"generator\" content=\"MediaWiki 1.36.0-wmf.25\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin-when-crossorigin\"/>\r\n"
			+ "<meta name=\"referrer\" content=\"origin-when-cross-origin\"/>\r\n"
			+ "<meta property=\"og:image\" content=\"https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Top_of_Atmosphere.jpg/1200px-Top_of_Atmosphere.jpg\"/>\r\n"
			+ "<link rel=\"preconnect\" href=\"//upload.wikimedia.org\"/>\r\n"
			+ "<link rel=\"alternate\" media=\"only screen and (max-width: 720px)\" href=\"//en.m.wikipedia.org/wiki/Aerospace\"/>\r\n"
			+ "<link rel=\"alternate\" type=\"application/x-wiki\" title=\"Edit this page\" href=\"/w/index.php?title=Aerospace&amp;action=edit\"/>\r\n"
			+ "<link rel=\"edit\" title=\"Edit this page\" href=\"/w/index.php?title=Aerospace&amp;action=edit\"/>\r\n"
			+ "<link rel=\"apple-touch-icon\" href=\"/static/apple-touch/wikipedia.png\"/>\r\n"
			+ "<link rel=\"shortcut icon\" href=\"/static/favicon/wikipedia.ico\"/>\r\n"
			+ "<link rel=\"search\" type=\"application/opensearchdescription+xml\" href=\"/w/opensearch_desc.php\" title=\"Wikipedia (en)\"/>\r\n"
			+ "<link rel=\"EditURI\" type=\"application/rsd+xml\" href=\"//en.wikipedia.org/w/api.php?action=rsd\"/>\r\n"
			+ "<link rel=\"license\" href=\"//creativecommons.org/licenses/by-sa/3.0/\"/>\r\n"
			+ "<link rel=\"canonical\" href=\"https://en.wikipedia.org/wiki/Aerospace\"/>\r\n"
			+ "<link rel=\"dns-prefetch\" href=\"//login.wikimedia.org\"/>\r\n"
			+ "<link rel=\"dns-prefetch\" href=\"//meta.wikimedia.org\" />\r\n" + "</head>";
	String TEXT_SEPARATION_INPUT = "   <div class=\"tiles\">\r\n" + "                <ul class=\"tiles-list\">\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://cars.av.by/\">\r\n"
			+ "                            <div style=\"top: 3px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"71\" height=\"31\"><use xlink:href=\"#car\"></use></svg>\r\n"
			+ "                            </div>\r\n" + "                            <span>Автомобили</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://truck.av.by/\">\r\n"
			+ "                            <div style=\"top: 2px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"67\" height=\"34\"><use xlink:href=\"#truck\"></use></svg>\r\n"
			+ "                            </div>\r\n"
			+ "                            <span>Грузовой транспорт</span>\r\n" + "                        </a>\r\n"
			+ "                    </li>\r\n" + "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://bus.av.by\">\r\n"
			+ "                            <div style=\"top: 5px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"71\" height=\"29\"><use xlink:href=\"#bus\"></use></svg>\r\n"
			+ "                            </div>\r\n"
			+ "                            <span>Автобусы и микроавтобусы</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://moto.av.by/\">\r\n" + "                            <div>\r\n"
			+ "                                <svg role=\"img\" width=\"58\" height=\"38\"><use xlink:href=\"#motorcycle\"></use></svg>\r\n"
			+ "                            </div>\r\n" + "                            <span>Мототехника</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://spec.av.by\">\r\n"
			+ "                            <div style=\"top: -1px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"54\" height=\"38\"><use xlink:href=\"#special\"></use></svg>\r\n"
			+ "                            </div>\r\n" + "                            <span>Спецтехника</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://agro.av.by\">\r\n"
			+ "                            <div style=\"top: 1px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"54\" height=\"37\"><use xlink:href=\"#agrimotor\"></use></svg>\r\n"
			+ "                            </div>\r\n" + "                            <span>С/х техника</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n"
			+ "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://trailer.av.by\">\r\n"
			+ "                            <div style=\"top: 9px;\">\r\n"
			+ "                                <svg role=\"img\" width=\"71\" height=\"19\"><use xlink:href=\"#trailer\"></use></svg>\r\n"
			+ "                            </div>\r\n"
			+ "                            <span>Прицепы и полуприцепы</span>\r\n" + "                        </a>\r\n"
			+ "                    </li>\r\n" + "                    <li class=\"tiles-item\">\r\n"
			+ "                        <a href=\"https://boat.av.by\">\r\n" + "                            <div>\r\n"
			+ "                                <svg role=\"img\" width=\"68\" height=\"24\"><use xlink:href=\"#cutter\"></use></svg>\r\n"
			+ "                            </div>\r\n" + "                            <span>Водный транспорт</span>\r\n"
			+ "                        </a>\r\n" + "                    </li>\r\n" + "                </ul>\r\n"
			+ "            </div>\r\n" + "\r\n" + "            <div class=\"related related-main\">\r\n"
			+ "    <div class=\"related-header\">\r\n"
			+ "        <h4 class=\"related-title\">Самые интересные предложения сегодня</h4>\r\n" + "\r\n"
			+ "        <p class=\"related-side\"><a href=\"/pages/top\">Как сюда попасть?</a></p>\r\n"
			+ "    </div>\r\n" + "\r\n" + "    <div class=\"related-cards js-slider\">\r\n"
			+ "        <div class=\"related-card\">\r\n" + "    <div class=\"related-card-pic\">\r\n"
			+ "        <a href=\"https://cars.av.by/bmw/x5/100151621\">\r\n"
			+ "            <img src=\"https://avcdn.av.by/advertmedium/0000/1332/0655.jpeg\">\r\n" + "        </a>\r\n"
			+ "        <div class=\"related-card-labels\">\r\n" + "            <div class=\"itemlabel-top\">\r\n"
			+ "                <div class=\"itemlabel-top-mobile\" onclick=\"showModal('.js-modal-card-promote')\">\r\n"
			+ "                    <div class=\"itemlabel itemlabel--top\">ТОП &#9733;</div>\r\n"
			+ "                </div>\r\n" + "                <div class=\"itemlabel-top-desktop\">\r\n"
			+ "                    <div class=\"itemlabel itemlabel--top\">ТОП &#9733;</div>\r\n"
			+ "                    <div class=\"itemlabel-top-dropdown\">\r\n"
			+ "                        <div class=\"itemlabel-top-dropdown-title\">ТОП объявление</div>\r\n"
			+ "                        <div class=\"itemlabel-top-dropdown-desc\">Поднялось выше остальных и собирает больше просмотров</div>\r\n"
			+ "                        <a href=\"pages/promo\">Способы ускорения продажи</a>\r\n"
			+ "                    </div>\r\n" + "                </div>\r\n" + "            </div>\r\n"
			+ "            <%is_vin_check%>\r\n" + "        </div>\r\n" + "    </div>";

	String TEXT_SEPARATION_EXPECTATION = "      Автомобили       Грузовой транспорт       Автобусы и микроавтобусы       Мототехника       Спецтехника       С/х техника       Прицепы и полуприцепы       Водный транспорт      Самые интересные предложения сегодня  Как сюда попасть?            ТОП ★    ТОП ★   ТОП объявление  Поднялось выше остальных и собирает больше просмотров  Способы ускорения продажи       ";
	String TEXT_FOR_WORDS_COUNT = "Our core Java programming tutorial is designed for students and working professionals. Java is an object-oriented, class-based, concurrent, secured and general-purpose computer-programming language. It is a widely used robust technology.\r\n" + 
			"Java is a programming language and a platform. Java is a high level, robust, object-oriented and secure programming language.\r\n" + 
			"Java was developed by Sun Microsystems (which is now the subsidiary of Oracle) in the year 1995. James Gosling is known as the father of Java. Before Java, its name was Oak. Since Oak was already a registered company, so James Gosling and his team changed the Oak name to Java.\r\n" + 
			"Platform: Any hardware or software environment in which a program runs, is known as a platform. Since Java has a runtime environment (JRE) and API, it is called a platform.\r\n";
}
